import Hoffman

#print axioms Hoffman.gapParameter_pos
#print axioms Hoffman.gapParameter_lt_one
#print axioms Hoffman.offset_gapParameter_le
#print axioms Hoffman.exclusion_radius_small
#print axioms Hoffman.gridResolution_pos
#print axioms Hoffman.grid_mesh_small
#print axioms Hoffman.offset_radius_ratio
#print axioms Hoffman.coverageProbability_pos
#print axioms Hoffman.one_add_inv_pow_le_exp
#print axioms Hoffman.coverageProbability_inv_eq
#print axioms Hoffman.colorBound_eq_explicit
#print axioms Hoffman.coverageProbability_inv_le
#print axioms Hoffman.dimension_log_ge_one
#print axioms Hoffman.grid_log_bound
#print axioms Hoffman.colorBound_le
#print axioms Hoffman.unitDistanceGraph_adj_iff_coordinates
#print axioms Hoffman.ordinary_chromaticNumber_le
#print axioms Hoffman.ordinary_chromaticNumber_finite
#print axioms Hoffman.chromaticReal_le
#print axioms Hoffman.chromatic_root_le_envelope
#print axioms Hoffman.rootEnvelope_tendsto
#print axioms Hoffman.chromatic_root_limsup
#print axioms Hoffman.covering_failure_lt_one
#print axioms Hoffman.base_sq
#print axioms Hoffman.exclusionRegion_subset_ball
#print axioms Hoffman.exclusionRegion_volume_le
#print axioms Hoffman.finite_upper_bound
#print axioms Hoffman.radius_offset
#print axioms Hoffman.parameters
#print axioms Hoffman.normalized_halfspace_iff
#print axioms Hoffman.same_core_distance_le
#print axioms Hoffman.different_cores_distance_ge
#print axioms Hoffman.core_union_avoids_gap
#print axioms Hoffman.gap_implies_unit_distance_free
#print axioms Hoffman.far_center_does_not_cut
#print axioms Hoffman.radial_exclusion_iff
#print axioms Hoffman.radial_reach_pos
#print axioms Hoffman.core_translate_iff
#print axioms Hoffman.coreUnion_translate_iff
#print axioms Hoffman.coreUnion_periodic
#print axioms Hoffman.isClosed_halfspace
#print axioms Hoffman.isClosed_core
#print axioms Hoffman.measurableSet_core
#print axioms Hoffman.measurableSet_coreUnion
#print axioms Hoffman.colorBound_periodic_borel
#print axioms Hoffman.main_upper_bound_explicit
#print axioms Hoffman.main_upper_bound
#print axioms Hoffman.momentCoeff_nonneg
#print axioms Hoffman.momentCoeff_zero
#print axioms Hoffman.momentPolynomial_mono
#print axioms Hoffman.one_le_momentPolynomial
#print axioms Hoffman.momentPolynomial_pos
#print axioms Hoffman.momentPolynomial_le_at_one
#print axioms Hoffman.isOpen_openNeighborhood
#print axioms Hoffman.neighborhood_unit_distance_free
#print axioms Hoffman.firstColor_mem
#print axioms Hoffman.measurable_firstColor
#print axioms Hoffman.firstColor_lt
#print axioms Hoffman.firstColor_invariant
#print axioms Hoffman.borel_coloring_of_robust_cover
#print axioms Hoffman.configurationCenters_periodic
#print axioms Hoffman.configurationCore_periodic
#print axioms Hoffman.localVector_projection
#print axioms Hoffman.nearCenters_conflict
#print axioms Hoffman.survivalEvent_mem_core
#print axioms Hoffman.openNeighborhood_periodic
#print axioms Hoffman.periodic_borel_coloring_of_robust_cover
#print axioms Hoffman.quotient_net_coloring
#print axioms Hoffman.base_pos
#print axioms Hoffman.planar_deficit_identity
#print axioms Hoffman.triangleArea_le
#print axioms Hoffman.triangleArea_half
#print axioms Hoffman.triangleArea_eq_iff
#print axioms Hoffman.twice_maximum_eq_base
#print axioms Hoffman.poisson_size_biased_hasSum
#print axioms Hoffman.poisson_void_density_hasSum
#print axioms Hoffman.survival_density_lower
#print axioms Hoffman.exists_samples_hitting_sets
#print axioms Hoffman.exists_translates_cover_finite
#print axioms Hoffman.random_net_coloring
#print axioms Hoffman.survivalEvent_measurable
#print axioms Hoffman.survivalEvent_measure
#print axioms Hoffman.survivalEvents_disjoint
#print axioms Hoffman.any_survival_measure
#print axioms Hoffman.bernoulli_survival
#print axioms Hoffman.normalized_survival_lower
#print axioms Hoffman.any_survival_lower
#print axioms Hoffman.main_upper_bound_coordinates
#print axioms Hoffman.ordinary_chromatic_value_exact
#print axioms Hoffman.torusProjection_representative
#print axioms Hoffman.torusProjection_surjective
#print axioms Hoffman.torusRepresentative_measurable
#print axioms Hoffman.torusProjection_measurable
#print axioms Hoffman.torusVolume_univ
#print axioms Hoffman.representative_mem_cube
#print axioms Hoffman.representative_projection
#print axioms Hoffman.ball_subset_cube
#print axioms Hoffman.torusProjection_measurePreserving
#print axioms Hoffman.torusBall_measurable
#print axioms Hoffman.projection_mem_torusBall
#print axioms Hoffman.torusBall_volume
#print axioms Hoffman.torus_kernel_norm
#print axioms Hoffman.torusBall_probability
#print axioms Hoffman.torusBall_probability_pos
#print axioms Hoffman.euclidean_norm_le_sum
#print axioms Hoffman.periodic_grid_net
#print axioms Hoffman.periodBasis_projection
#print axioms Hoffman.ballMass_pos
#print axioms Hoffman.ballMass_le_one
#print axioms Hoffman.ofReal_ballMass
#print axioms Hoffman.ballMass_eq
#print axioms Hoffman.ballMass_ratio
#print axioms Hoffman.torus_near_measurable
#print axioms Hoffman.torus_near_mass
#print axioms Hoffman.torus_forbiddenCenter_measurable
#print axioms Hoffman.torus_survival_lower
